### ISSUE TITLE
Maybe a hardcoded secret

### ISSUE THREAD

**Issue by SlimTrabelsi** [sapbrussels/intelligenthighway_physicalmodel#2]
Hi,

There is a hardcoded secret in this portion of code https://github.com/sapbrussels/intelligenthighway_physicalmodel/blob/3a30c20c1a5d57a198c8499197e028ececf1c156/scripts/trigger_command.js#L4

Thank you
best

**Comment by cedricve** [comment]
the tenant is no longer onboarded.
